# Generated by Django 3.0 on 2019-12-11 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('repo_url', models.URLField(blank=True, verbose_name='Repository URL')),
                ('site_url', models.URLField(blank=True, max_length=2000, verbose_name='Site URL')),
                ('image', models.ImageField(upload_to='')),
                ('technologies', models.ManyToManyField(related_name='projects', to='projects.Technology')),
            ],
        ),
    ]
